[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "PowerPoint automation with MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "python-pptx>=0.6.21",
]
